# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 339535ff39dc0748ec79220bb05072db054d2b7561f3177276df9430e0688beb50bab45ecef6c9db454ef5c6b138be84d87ab55a01db3061600b4a2115117f9e

test:
  secret_key_base: 847805cb3afc9292c87401d1e79a878b25b424fb47da6e27007a49b6b5f42f85b19a30b527da94c80d693b0056704ab84bc349d9d655b440bad662565e20f8b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
